theme = "hugo-theme-bootstrap4-blog"
baseurl = "http://haibin.github.io/"
languageCode = "en-us"
title = "Life As A Software Engineer"

[Params]
  Author = "Haibin Liu"
  disqusShortname = "haibin-github"